### ISSUE TITLE
Arrays vs Hashes blogpost feedback

### ISSUE THREAD

**Issue by Thrashmandicoot** [atp1o2/atp1o2.github.io#7]
http://atp1o2.github.io/blog/t3-arrays-hashes.html

Heya, hope all is well! Here's some feedback for this post:

I liked the metaphor comparing arrays to a grocery list. I felt the information was very condensed and hard to read though. You may want to consider separating out the content into sections for easier readability.

Another point to consider is that use of terms such as integer, without explanation may confuse a beginner type reader. Consider elaborating on terms the general public may not be used to.

**Comment by atp1o2** [comment]
Appreciate the feedback! I'll definitely work on those. I want to better the design format, tweak the coloring and paragraphing spacing, and proof-read the content to something I can be proud of showing before really advertise my blog more. Right now it's really rough, but knowing somebody visited it is definitely pushing me to work on it more
